const Currency = require('../models/currency');
const Package = require('../models/package');

const seedPackages = async () => {
  const packages = [
    { name_package: '1 Month Premium', price: 29900, days_duration: 30 },
    { name_package: '6 Month Premium', price: 129000, days_duration: 180 },
    { name_package: '1 Years Premium', price: 199000, days_duration: 360 },
    { name_package: 'Lifetime Premium', price: 299000, days_duration: 9999 },
  ];

  for (const pkg of packages) {
    await Package.findOrCreate({
      where: { name_package: pkg.name_package },
      defaults: pkg,
    });
  }

  console.log('Packages seeded successfully');
};

const seedCurrencies = async () => {
  const currencies = [
    { code: 'USD', name: 'United States Dollar', symbol: '$' },
    { code: 'EUR', name: 'Euro', symbol: '€' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
    { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr.' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$' },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱' },
    {
      code: 'IDR',
      name: 'Indonesian Rupiah',
      symbol: 'Rp',
      is_base_currency: true,
    },
    { code: 'THB', name: 'Thai Baht', symbol: '฿' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM' },
    { code: 'PLN', name: 'Polish Zloty', symbol: 'zł' },
    { code: 'VND', name: 'Vietnamese Dong', symbol: '₫' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
    { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£' },
    { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د' },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦' },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵' },
    { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh' },
    { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh' },
    { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.' },
    { code: 'DZD', name: 'Algerian Dinar', symbol: 'دج' },
    { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د' },
    { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت' },
    { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل' },
    { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا' },
    { code: 'QAR', name: 'Qatari Riyal', symbol: '﷼' },
    { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك' },
    { code: 'BHD', name: 'Bahraini Dinar', symbol: 'ب.د' },
    { code: 'OMR', name: 'Omani Rial', symbol: '﷼' },
    { code: 'BND', name: 'Brunei Dollar', symbol: 'B$' },
    { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨' },
    { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨' },
    { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K' },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴' },
    { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br' },
    { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼' },
    { code: 'GEL', name: 'Georgian Lari', symbol: '₾' },
    { code: 'AMD', name: 'Armenian Dram', symbol: '֏' },
    { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.' },
    { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn' },
    { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв.' },
    { code: 'RON', name: 'Romanian Leu', symbol: 'lei' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč' },
    { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr' },
    { code: 'EEK', name: 'Estonian Kroon', symbol: 'kr' },
    { code: 'LVL', name: 'Latvian Lats', symbol: 'Ls' },
    { code: 'LTL', name: 'Lithuanian Litas', symbol: 'Lt' },
    { code: 'MDL', name: 'Moldovan Leu', symbol: 'L' },
    { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮' },
    { code: 'IRR', name: 'Iranian Rial', symbol: '﷼' },
    { code: 'AFN', name: 'Afghan Afghani', symbol: '؋' },
    { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf' },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨' },
    { code: 'BWP', name: 'Botswana Pula', symbol: 'P' },
    { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK' },
    { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK' },
    { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu' },
    { code: 'CDF', name: 'Congolese Franc', symbol: 'FC' },
    { code: 'XAF', name: 'Central African CFA Franc', symbol: 'Fr' },
    { code: 'XOF', name: 'West African CFA Franc', symbol: 'Fr' },
    { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E' },
    { code: 'LSL', name: 'Lesotho Loti', symbol: 'L' },
    { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar' },
    { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨' },
    { code: 'RWF', name: 'Rwandan Franc', symbol: 'Fr' },
    { code: 'SOS', name: 'Somali Shilling', symbol: 'Sh' },
    { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fr' },
    { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk' },
    { code: 'SDG', name: 'Sudanese Pound', symbol: '£' },
    { code: 'SSP', name: 'South Sudanese Pound', symbol: '£' },
    { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT' },
    { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz' },
    { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$' },
    { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$' },
    { code: 'BBD', name: 'Barbadian Dollar', symbol: '$' },
    { code: 'BSD', name: 'Bahamian Dollar', symbol: '$' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: '$' },
    { code: 'GYD', name: 'Guyanese Dollar', symbol: '$' },
    { code: 'SRD', name: 'Surinamese Dollar', symbol: '$' },
    { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$' },
    { code: 'HTG', name: 'Haitian Gourde', symbol: 'G' },
    { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$' },
    { code: 'CUP', name: 'Cuban Peso', symbol: '$MN' },
    { code: 'CUC', name: 'Cuban Convertible Peso', symbol: '$' },
    { code: 'CLP', name: 'Chilean Peso', symbol: '$' },
    { code: 'COP', name: 'Colombian Peso', symbol: '$' },
    { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/.' },
    { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.' },
    { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲' },
    { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U' },
    { code: 'VEF', name: 'Venezuelan Bolívar', symbol: 'Bs.F' },
    { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
    { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден' },
    { code: 'ALL', name: 'Albanian Lek', symbol: 'L' },
    { code: 'SHP', name: 'Saint Helena Pound', symbol: '£' },
    { code: 'FJD', name: 'Fijian Dollar', symbol: '$' },
    { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$' },
    { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K' },
    { code: 'WST', name: 'Samoan Tala', symbol: 'WS$' },
    { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$' },
    { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT' },
    { code: 'KMF', name: 'Comorian Franc', symbol: 'CF' },
    { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$' },
    { code: 'MRO', name: 'Mauritanian Ouguiya', symbol: 'UM' },
    { code: 'NAD', name: 'Namibian Dollar', symbol: '$' },
    { code: 'BWP', name: 'Botswana Pula', symbol: 'P' },
    { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm' },
    { code: 'UZS', name: 'Uzbekistani Som', symbol: 'лв' },
  ];

  for (const currency of currencies) {
    await Currency.findOrCreate({
      where: { code: currency.code },
      defaults: currency,
    });
  }
};

module.exports = {
  seedCurrencies,
  seedPackages,
};
